export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';


/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

/* LOGOUT */
export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';

/* USER */
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAIL = 'GETUSER_FAIL';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

/* PARTICIPANTS */
export const PARTICIPANT_ADD_REQUEST = 'PARTICIPANT_ADD_REQUEST';
export const PARTICIPANT_ADD_SUCCESS = 'PARTICIPANT_ADD_SUCCESS';
export const PARTICIPANT_ADD_FAIL = 'PARTICIPANT_ADD_FAIL';
export const PARTICIPANT_UPDATE_REQUEST = 'PARTICIPANT_UPDATE_REQUEST';
export const PARTICIPANT_UPDATE_SUCCESS = 'PARTICIPANT_UPDATE_SUCCESS';
export const PARTICIPANT_UPDATE_FAIL = 'PARTICIPANT_UPDATE_FAIL';
export const PARTICIPANT_DELETE_REQUEST = 'PARTICIPANT_DELETE_REQUEST';
export const PARTICIPANT_DELETE_SUCCESS = 'PARTICIPANT_DELETE_SUCCESS';
export const PARTICIPANT_DELETE_FAIL = 'PARTICIPANT_DELETE_FAIL';
export const PARTICIPANT_GET_REQUEST = 'PARTICIPANT_GET_REQUEST';
export const PARTICIPANT_GET_SUCCESS = 'PARTICIPANT_GET_SUCCESS';
export const PARTICIPANT_GET_FAIL = 'PARTICIPANT_GET_FAIL';


/* PROGRAMS */
export const PROGRAM_ADD_REQUEST = 'PROGRAM_ADD_REQUEST';
export const PROGRAM_ADD_SUCCESS = 'PROGRAM_ADD_SUCCESS';
export const PROGRAM_ADD_FAIL = 'PROGRAM_ADD_FAIL';
export const PROGRAM_UPDATE_REQUEST = 'PROGRAM_UPDATE_REQUEST';
export const PROGRAM_UPDATE_SUCCESS = 'PROGRAM_UPDATE_SUCCESS';
export const PROGRAM_UPDATE_FAIL = 'PROGRAM_UPDATE_FAIL';
export const PROGRAM_DELETE_REQUEST = 'PROGRAM_DELETE_REQUEST';
export const PROGRAM_DELETE_SUCCESS = 'PROGRAM_DELETE_SUCCESS';
export const PROGRAM_DELETE_FAIL = 'PROGRAM_DELETE_FAIL';
export const PROGRAM_GET_REQUEST = 'PROGRAM_GET_REQUEST';
export const PROGRAM_GET_SUCCESS = 'PROGRAM_GET_SUCCESS';
export const PROGRAM_GET_FAIL = 'PROGRAM_GET_FAIL';

/* USERS */
export const USERS_ADD_REQUEST = 'USERS_ADD_REQUEST';
export const USERS_ADD_SUCCESS = 'USERS_ADD_SUCCESS';
export const USERS_ADD_FAIL = 'USERS_ADD_FAIL';
export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_FAIL = 'USERS_UPDATE_FAIL';
export const USERS_DELETE_REQUEST = 'USERS_DELETE_REQUEST';
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const USERS_DELETE_FAIL = 'USERS_DELETE_FAIL';
export const USERS_GET_REQUEST = 'USERS_GET_REQUEST';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_FAIL = 'USERS_GET_FAIL';

/* PRIVILEGES */
export const PRIVILEGES_ADD_REQUEST = 'PRIVILEGES_ADD_REQUEST';
export const PRIVILEGES_ADD_SUCCESS = 'PRIVILEGES_ADD_SUCCESS';
export const PRIVILEGES_ADD_FAIL = 'PRIVILEGES_ADD_FAIL';
export const PRIVILEGES_UPDATE_REQUEST = 'PRIVILEGES_UPDATE_REQUEST';
export const PRIVILEGES_UPDATE_SUCCESS = 'PRIVILEGES_UPDATE_SUCCESS';
export const PRIVILEGES_UPDATE_FAIL = 'PRIVILEGES_UPDATE_FAIL';
export const PRIVILEGES_DELETE_REQUEST = 'PRIVILEGES_DELETE_REQUEST';
export const PRIVILEGES_DELETE_SUCCESS = 'PRIVILEGES_DELETE_SUCCESS';
export const PRIVILEGES_DELETE_FAIL = 'PRIVILEGES_DELETE_FAIL';
export const PRIVILEGES_GET_REQUEST = 'PRIVILEGES_GET_REQUEST';
export const PRIVILEGES_GET_SUCCESS = 'PRIVILEGES_GET_SUCCESS';
export const PRIVILEGES_GET_ALL_SUCCESS = 'PRIVILEGES_GET_ALL_SUCCESS';
export const PRIVILEGES_GET_FAIL = 'PRIVILEGES_GET_FAIL';

/* EDUCATORS */
export const EDUCATORS_ADD_REQUEST = 'EDUCATORS_ADD_REQUEST';
export const EDUCATORS_ADD_SUCCESS = 'EDUCATORS_ADD_SUCCESS';
export const EDUCATORS_ADD_FAIL = 'EDUCATORS_ADD_FAIL';
export const EDUCATORS_UPDATE_REQUEST = 'EDUCATORS_UPDATE_REQUEST';
export const EDUCATORS_UPDATE_SUCCESS = 'EDUCATORS_UPDATE_SUCCESS';
export const EDUCATORS_UPDATE_FAIL = 'EDUCATORS_UPDATE_FAIL';
export const EDUCATORS_DELETE_REQUEST = 'EDUCATORS_DELETE_REQUEST';
export const EDUCATORS_DELETE_SUCCESS = 'EDUCATORS_DELETE_SUCCESS';
export const EDUCATORS_DELETE_FAIL = 'EDUCATORS_DELETE_FAIL';
export const EDUCATORS_GET_REQUEST = 'EDUCATORS_GET_REQUEST';
export const EDUCATORS_GET_SUCCESS = 'EDUCATORS_GET_SUCCESS';
export const EDUCATORS_GET_FAIL = 'EDUCATORS_GET_FAIL';

/* CATALOGS */
export const CATALOGS_ADD_REQUEST = 'CATALOGS_ADD_REQUEST';
export const CATALOGS_ADD_SUCCESS = 'CATALOGS_ADD_SUCCESS';
export const CATALOGS_ADD_FAIL = 'CATALOGS_ADD_FAIL';
export const CATALOGS_UPDATE_REQUEST = 'CATALOGS_UPDATE_REQUEST';
export const CATALOGS_UPDATE_SUCCESS = 'CATALOGS_UPDATE_SUCCESS';
export const CATALOGS_UPDATE_FAIL = 'CATALOGS_UPDATE_FAIL';
export const CATALOGS_DELETE_REQUEST = 'CATALOGS_DELETE_REQUEST';
export const CATALOGS_DELETE_SUCCESS = 'CATALOGS_DELETE_SUCCESS';
export const CATALOGS_DELETE_FAIL = 'CATALOGS_DELETE_FAIL';
export const CATALOGS_GET_REQUEST = 'CATALOGS_GET_REQUEST';
export const CATALOGS_GET_SUCCESS = 'CATALOGS_GET_SUCCESS';
export const CATALOGS_GET_FAIL = 'CATALOGS_GET_FAIL';

/* SEDES */
export const SEDES_ADD_REQUEST = 'SEDES_ADD_REQUEST';
export const SEDES_ADD_SUCCESS = 'SEDES_ADD_SUCCESS';
export const SEDES_ADD_FAIL = 'SEDES_ADD_FAIL';
export const SEDES_UPDATE_REQUEST = 'SEDES_UPDATE_REQUEST';
export const SEDES_UPDATE_SUCCESS = 'SEDES_UPDATE_SUCCESS';
export const SEDES_UPDATE_FAIL = 'SEDES_UPDATE_FAIL';
export const SEDES_DELETE_REQUEST = 'SEDES_DELETE_REQUEST';
export const SEDES_DELETE_SUCCESS = 'SEDES_DELETE_SUCCESS';
export const SEDES_DELETE_FAIL = 'SEDES_DELETE_FAIL';
export const SEDES_GET_REQUEST = 'SEDES_GET_REQUEST';
export const SEDES_GET_SUCCESS = 'SEDES_GET_SUCCESS';
export const SEDES_GET_FAIL = 'SEDES_GET_FAIL';

/* PROGRAM_ACTIVATION */
export const PROGRAM_ACTIVATIONS_GET_REQUEST = 'PROGRAM_ACTIVATIONS_GET_REQUEST';
export const PROGRAM_ACTIVATIONS_GET_SUCCESS = 'PROGRAM_ACTIVATIONS_GET_SUCCESS';
export const PROGRAM_ACTIVATIONS_GET_FAIL = 'PROGRAM_ACTIVATIONS_GET_FAIL';
export const PROGRAM_ACTIVATIONS_ADD_REQUEST = 'PROGRAM_ACTIVATIONS_ADD_REQUEST';
export const PROGRAM_ACTIVATIONS_ADD_SUCCESS = 'PROGRAM_ACTIVATIONS_ADD_SUCCESS';
export const PROGRAM_ACTIVATIONS_ADD_FAIL = 'PROGRAM_ACTIVATIONS_ADD_FAIL';
export const PROGRAM_ACTIVATIONS_DELETE_REQUEST = 'PROGRAM_ACTIVATIONS_DELETE_REQUEST';
export const PROGRAM_ACTIVATIONS_DELETE_SUCCESS = 'PROGRAM_ACTIVATIONS_DELETE_SUCCESS';
export const PROGRAM_ACTIVATIONS_DELETE_FAIL = 'PROGRAM_ACTIVATIONS_DELETE_FAIL';
export const PROGRAM_ACTIVATIONS_UPDATE_REQUEST = 'PROGRAM_ACTIVATIONS_UPDATE_REQUEST';
export const PROGRAM_ACTIVATIONS_UPDATE_SUCCESS = 'PROGRAM_ACTIVATIONS_UPDATE_SUCCESS';
export const PROGRAM_ACTIVATIONS_UPDATE_FAIL = 'PROGRAM_ACTIVATIONS_UPDATE_FAIL';

/* PARTICIPANT_CONTACT*/
export const PARTICIPANT_CONTACT_ADD_REQUEST = 'PARTICIPANT_CONTACT_ADD_REQUEST';
export const PARTICIPANT_CONTACT_ADD_SUCCESS = 'PARTICIPANT_CONTACT_ADD_SUCCESS';
export const PARTICIPANT_CONTACT_ADD_FAIL = 'PARTICIPANT_CONTACT_ADD_FAIL';
export const PARTICIPANT_CONTACT_UPDATE_REQUEST = 'PARTICIPANT_CONTACT_UPDATE_REQUEST';
export const PARTICIPANT_CONTACT_UPDATE_SUCCESS = 'PARTICIPANT_CONTACT_UPDATE_SUCCESS';
export const PARTICIPANT_CONTACT_UPDATE_FAIL = 'PARTICIPANT_CONTACT_UPDATE_FAIL';
export const PARTICIPANT_CONTACT_DELETE_REQUEST = 'PARTICIPANT_CONTACT_DELETE_REQUEST';
export const PARTICIPANT_CONTACT_DELETE_SUCCESS = 'PARTICIPANT_CONTACT_DELETE_SUCCESS';
export const PARTICIPANT_CONTACT_DELETE_FAIL = 'PARTICIPANT_CONTACT_DELETE_FAIL';
export const PARTICIPANT_CONTACT_GET_REQUEST = 'PARTICIPANT_CONTACT_GET_REQUEST';
export const PARTICIPANT_CONTACT_GET_SUCCESS = 'PARTICIPANT_CONTACT_GET_SUCCESS';
export const PARTICIPANT_CONTACT_GET_FAIL = 'PARTICIPANT_CONTACT_GET_FAIL';
export const PARTICIPANT_CONTACT_GET_BY_PARTICIPANTID_REQUEST = 'PARTICIPANT_CONTACT_GET_BY_PARTICIPANTID_REQUEST';
export const PARTICIPANT_CONTACT_GET_BY_PARTICIPANTID_SUCCESS = 'PARTICIPANT_CONTACT_GET_BY_PARTICIPANTID_SUCCESS';
export const PARTICIPANT_CONTACT_GET_BY_PARTICIPANTID_FAIL = 'PARTICIPANT_CONTACT_GET_BY_PARTICIPANTID_FAIL';

/* COURSES */
export const COURSES_ADD_REQUEST = 'COURSES_ADD_REQUEST';
export const COURSES_ADD_SUCCESS = 'COURSES_ADD_SUCCESS';
export const COURSES_ADD_FAIL = 'COURSES_ADD_FAIL';
export const COURSES_UPDATE_REQUEST = 'COURSES_UPDATE_REQUEST';
export const COURSES_UPDATE_SUCCESS = 'COURSES_UPDATE_SUCCESS';
export const COURSES_UPDATE_FAIL = 'COURSES_UPDATE_FAIL';
export const COURSES_DELETE_REQUEST = 'COURSES_DELETE_REQUEST';
export const COURSES_DELETE_SUCCESS = 'COURSES_DELETE_SUCCESS';
export const COURSES_DELETE_FAIL = 'COURSES_DELETE_FAIL';
export const COURSES_GET_REQUEST = 'COURSES_GET_REQUEST';
export const COURSES_GET_SUCCESS = 'COURSES_GET_SUCCESS';
export const COURSES_GET_FAIL = 'COURSES_GET_FAIL';

/* GRADES */
export const GRADES_ADD_REQUEST = 'GRADES_ADD_REQUEST';
export const GRADES_ADD_SUCCESS = 'GRADES_ADD_SUCCESS';
export const GRADES_ADD_FAIL = 'GRADES_ADD_FAIL';
export const GRADES_UPDATE_REQUEST = 'GRADES_UPDATE_REQUEST';
export const GRADES_UPDATE_SUCCESS = 'GRADES_UPDATE_SUCCESS';
export const GRADES_UPDATE_FAIL = 'GRADES_UPDATE_FAIL';
export const GRADES_DELETE_REQUEST = 'GRADES_DELETE_REQUEST';
export const GRADES_DELETE_SUCCESS = 'GRADES_DELETE_SUCCESS';
export const GRADES_DELETE_FAIL = 'GRADES_DELETE_FAIL';
export const GRADES_GET_REQUEST = 'GRADES_GET_REQUEST';
export const GRADES_GET_SUCCESS = 'GRADES_GET_SUCCESS';
export const GRADES_GET_FAIL = 'GRADES_GET_FAIL';

/* WORKSHOPS */
export const WORKSHOPS_ADD_REQUEST = 'WORKSHOPS_ADD_REQUEST';
export const WORKSHOPS_ADD_SUCCESS = 'WORKSHOPS_ADD_SUCCESS';
export const WORKSHOPS_ADD_FAIL = 'WORKSHOPS_ADD_FAIL';
export const WORKSHOPS_UPDATE_REQUEST = 'WORKSHOPS_UPDATE_REQUEST';
export const WORKSHOPS_UPDATE_SUCCESS = 'WORKSHOPS_UPDATE_SUCCESS';
export const WORKSHOPS_UPDATE_FAIL = 'WORKSHOPS_UPDATE_FAIL';
export const WORKSHOPS_DELETE_REQUEST = 'WORKSHOPS_DELETE_REQUEST';
export const WORKSHOPS_DELETE_SUCCESS = 'WORKSHOPS_DELETE_SUCCESS';
export const WORKSHOPS_DELETE_FAIL = 'WORKSHOPS_DELETE_FAIL';
export const WORKSHOPS_GET_REQUEST = 'WORKSHOPS_GET_REQUEST';
export const WORKSHOPS_GET_SUCCESS = 'WORKSHOPS_GET_SUCCESS';
export const WORKSHOPS_GET_FAIL = 'WORKSHOPS_GET_FAIL';

/* DASHBOARD */
export const DASHBOARD_STATBOXES_GET_REQUEST = 'DASHBOARD_STATBOXES_GET_REQUEST';
export const DASHBOARD_STATBOXES_GET_SUCCESS = 'DASHBOARD_STATBOXES_GET_SUCCESS';
export const DASHBOARD_STATBOXES_GET_FAIL = 'DASHBOARD_STATBOXES_GET_FAIL';

/* CATEGORIES */
export const CATEGORIES_ADD_REQUEST = 'CATEGORIES_ADD_REQUEST';
export const CATEGORIES_ADD_SUCCESS = 'CATEGORIES_ADD_SUCCESS';
export const CATEGORIES_ADD_FAIL = 'CATEGORIES_ADD_FAIL';
export const CATEGORIES_UPDATE_REQUEST = 'CATEGORIES_UPDATE_REQUEST';
export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_UPDATE_FAIL = 'CATEGORIES_UPDATE_FAIL';
export const CATEGORIES_DELETE_REQUEST = 'CATEGORIES_DELETE_REQUEST';
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_DELETE_FAIL = 'CATEGORIES_DELETE_FAIL';
export const CATEGORIES_GET_REQUEST = 'CATEGORIES_GET_REQUEST';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAIL = 'CATEGORIES_GET_FAIL';
