export var data_types = {
  "Texto": "text",
  "Número": "number",
  "Decimal": "decimal",
  "Color": "color",
  "Dirección web": "url",
  "Fecha": "date",
  "Fecha con tiempo": "datetime-local",
  "Email": "email",
  "Rango": "range"
};

export const evaluationPeriods = {
  "mensual": 1,
  "bimestral": 2,
  "trimestral": 3,
  "semestral": 6,
  "anual": 12
};

export var privileges = {
  "Admin": 2,
  "Teacher": 1,
  "No Privilege": 0,
};

export var personal_documents = {
  "dpi": "dpi",
  "pasaporte": "passport",
  "licencia": "license"
};

export var gender = {
  "hombre": "male",
  "mujer": "female"
};

export var countries = {
  "Guatemala": "Guatemala",
  "Afganistán": "Afghanistan",
  "Albania": "Albania",
  "Alemania": "Germany",
  "Algeria": "Algeria",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Anguila": "Anguilla",
  "Antártida": "Antarctica",
  "Antigua y Barbuda": "Antigua and Barbuda",
  "Antillas Neerlandesas": "Netherlands Antilles",
  "Arabia Saudita": "Saudi Arabia",
  "Argentina": "Argentina",
  "Armenia": "Armenia",
  "Aruba": "Aruba",
  "Australia": "Australia",
  "Austria": "Austria",
  "Azerbayán": "Azerbaijan",
  "Bélgica": "Belgium",
  "Bahamas": "Bahamas",
  "Bahrein": "Bahrain",
  "Bangladesh": "Bangladesh",
  "Barbados": "Barbados",
  "Belice": "Belize",
  "Benín": "Benin",
  "Bhután": "Bhutan",
  "Bielorrusia": "Belarus",
  "Birmania": "Myanmar",
  "Bolivia": "Bolivia",
  "Bosnia y Herzegovina": "Bosnia and Herzegovina",
  "Botsuana": "Botswana",
  "Brasil": "Brazil",
  "Brunéi": "Brunei",
  "Bulgaria": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cabo Verde": "Cape Verde",
  "Camboya": "Cambodia",
  "Camerún": "Cameroon",
  "Canadá": "Canada",
  "Chad": "Chad",
  "Chile": "Chile",
  "China": "China",
  "Chipre": "Cyprus",
  "Ciudad del Vaticano": "Vatican City State",
  "Colombia": "Colombia",
  "Comoras": "Comoros",
  "Congo": "Congo",
  "Corea del Norte": "North Korea",
  "Corea del Sur": "South Korea",
  "Costa de Marfil": "Ivory Coast",
  "Costa Rica": "Costa Rica",
  "Croacia": "Croatia",
  "Cuba": "Cuba",
  "Dinamarca": "Denmark",
  "Dominica": "Dominica",
  "Ecuador": "Ecuador",
  "Egipto": "Egypt",
  "El Salvador": "El Salvador",
  "Emiratos Árabes Unidos": "United Arab Emirates",
  "Eritrea": "Eritrea",
  "Eslovaquia": "Slovakia",
  "Eslovenia": "Slovenia",
  "España": "Spain",
  "Estados Unidos de América": "United States of America",
  "Estonia": "Estonia",
  "Etiopía": "Ethiopia",
  "Filipinas": "Philippines",
  "Finlandia": "Finland",
  "Fiyi": "Fiji",
  "Francia": "France",
  "Gabón": "Gabon",
  "Gambia": "Gambia",
  "Georgia": "Georgia",
  "Ghana": "Ghana",
  "Gibraltar": "Gibraltar",
  "Granada": "Grenada",
  "Grecia": "Greece",
  "Groenlandia": "Greenland",
  "Guadalupe": "Guadeloupe",
  "Guam": "Guam",
  "Guayana Francesa": "French Guiana",
  "Guernsey": "Guernsey",
  "Guinea": "Guinea",
  "Guinea Ecuatorial": "Equatorial Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  "Guyana": "Guyana",
  "Haití": "Haiti",
  "Honduras": "Honduras",
  "Hong kong": "Hong Kong",
  "Hungría": "Hungary",
  "India": "India",
  "Indonesia": "Indonesia",
  "Irán": "Iran",
  "Irak": "Iraq",
  "Irlanda": "Ireland",
  "Isla Bouvet": "Bouvet Island",
  "Isla de Man": "Isle of Man",
  "Isla de Navidad": "Christmas Island",
  "Isla Norfolk": "Norfolk Island",
  "Islandia": "Iceland",
  "Islas Bermudas": "Bermuda Islands",
  "Islas Caimán": "Cayman Islands",
  "Islas Cocos (Keeling)": "Cocos (Keeling) Islands",
  "Islas Cook": "Cook Islands",
  "Islas de Åland": "Åland Islands",
  "Islas Feroe": "Faroe Islands",
  "Islas Georgias del Sur y Sandwich del Sur": "South Georgia and the South Sandwich Islands",
  "Islas Heard y McDonald": "Heard Island and McDonald Islands",
  "Islas Maldivas": "Maldives",
  "Islas Malvinas": "Falkland Islands (Malvinas)",
  "Islas Marianas del Norte": "Northern Mariana Islands",
  "Islas Marshall": "Marshall Islands",
  "Islas Pitcairn": "Pitcairn Islands",
  "Islas Salomón": "Solomon Islands",
  "Islas Turcas y Caicos": "Turks and Caicos Islands",
  "Islas Ultramarinas Menores de Estados Unidos": "United States Minor Outlying Islands",
  "Islas Vírgenes Británicas": "Virgin Islands",
  "Islas Vírgenes de los Estados Unidos": "United States Virgin Islands",
  "Israel": "Israel",
  "Italia": "Italy",
  "Jamaica": "Jamaica",
  "Japón": "Japan",
  "Jersey": "Jersey",
  "Jordania": "Jordan",
  "Kazajistán": "Kazakhstan",
  "Kenia": "Kenya",
  "Kirgizstán": "Kyrgyzstan",
  "Kiribati": "Kiribati",
  "Kuwait": "Kuwait",
  "Líbano": "Lebanon",
  "Laos": "Laos",
  "Lesoto": "Lesotho",
  "Letonia": "Latvia",
  "Liberia": "Liberia",
  "Libia": "Libya",
  "Liechtenstein": "Liechtenstein",
  "Lituania": "Lithuania",
  "Luxemburgo": "Luxembourg",
  "México": "Mexico",
  "Mónaco": "Monaco",
  "Macao": "Macao",
  "Macedônia": "Macedonia",
  "Madagascar": "Madagascar",
  "Malasia": "Malaysia",
  "Malawi": "Malawi",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marruecos": "Morocco",
  "Martinica": "Martinique",
  "Mauricio": "Mauritius",
  "Mauritania": "Mauritania",
  "Mayotte": "Mayotte",
  "Micronesia": "Estados Federados de",
  "Moldavia": "Moldova",
  "Mongolia": "Mongolia",
  "Montenegro": "Montenegro",
  "Montserrat": "Montserrat",
  "Mozambique": "Mozambique",
  "Namibia": "Namibia",
  "Nauru": "Nauru",
  "Nepal": "Nepal",
  "Nicaragua": "Nicaragua",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "Niue": "Niue",
  "Noruega": "Norway",
  "Nueva Caledonia": "New Caledonia",
  "Nueva Zelanda": "New Zealand",
  "Omán": "Oman",
  "Países Bajos": "Netherlands",
  "Pakistán": "Pakistan",
  "Palau": "Palau",
  "Palestina": "Palestine",
  "Panamá": "Panama",
  "Papúa Nueva Guinea": "Papua New Guinea",
  "Paraguay": "Paraguay",
  "Perú": "Peru",
  "Polinesia Francesa": "French Polynesia",
  "Polonia": "Poland",
  "Portugal": "Portugal",
  "Puerto Rico": "Puerto Rico",
  "Qatar": "Qatar",
  "Reino Unido": "United Kingdom",
  "República Centroafricana": "Central African Republic",
  "República Checa": "Czech Republic",
  "República Dominicana": "Dominican Republic",
  "Reunión": "Réunion",
  "Ruanda": "Rwanda",
  "Rumanía": "Romania",
  "Rusia": "Russia",
  "Sahara Occidental": "Western Sahara",
  "Samoa": "Samoa",
  "Samoa Americana": "American Samoa",
  "San Bartolomé": "Saint Barthélemy",
  "San Cristóbal y Nieves": "Saint Kitts and Nevis",
  "San Marino": "San Marino",
  "San Martín (Francia)": "Saint Martin (French part)",
  "San Pedro y Miquelón": "Saint Pierre and Miquelon",
  "San Vicente y las Granadinas": "Saint Vincent and the Grenadines",
  "Santa Elena": "Ascensión y Tristán de Acuña",
  "Santa Lucía": "Saint Lucia",
  "Santo Tomé y Príncipe": "Sao Tome and Principe",
  "Senegal": "Senegal",
  "Serbia": "Serbia",
  "Seychelles": "Seychelles",
  "Sierra Leona": "Sierra Leone",
  "Singapur": "Singapore",
  "Siria": "Syria",
  "Somalia": "Somalia",
  "Sri lanka": "Sri Lanka",
  "Sudáfrica": "South Africa",
  "Sudán": "Sudan",
  "Suecia": "Sweden",
  "Suiza": "Switzerland",
  "Surinám": "Suriname",
  "Svalbard y Jan Mayen": "Svalbard and Jan Mayen",
  "Swazilandia": "Swaziland",
  "Tadjikistán": "Tajikistan",
  "Tailandia": "Thailand",
  "Taiwán": "Taiwan",
  "Tanzania": "Tanzania",
  "Territorio Británico del Océano Índico": "British Indian Ocean Territory",
  "Territorios Australes y Antárticas Franceses": "French Southern Territories",
  "Timor Oriental": "East Timor",
  "Togo": "Togo",
  "Tokelau": "Tokelau",
  "Tonga": "Tonga",
  "Trinidad y Tobago": "Trinidad and Tobago",
  "Tunez": "Tunisia",
  "Turkmenistán": "Turkmenistan",
  "Turquía": "Turkey",
  "Tuvalu": "Tuvalu",
  "Ucrania": "Ukraine",
  "Uganda": "Uganda",
  "Uruguay": "Uruguay",
  "Uzbekistán": "Uzbekistan",
  "Vanuatu": "Vanuatu",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Wallis y Futuna": "Wallis and Futuna",
  "Yemen": "Yemen",
  "Yibuti": "Djibouti",
  "Zambia": "Zambia",
  "Zimbabue": "Zimbabwe"
};

export var typeCategory = {
  "division": "division",
  "section": "section",
  "workshop": "workshop",
  "course": "course"
};
