/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';
/* USER */
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAIL = 'GETUSER_FAIL';
export const SET_USER_TYPE = 'SET_USER_TYPE';

/*FORGOT PASSWORD */
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
//DASHOARD
export const DASHBOARD_STATBOXES_GET_FAIL = 'DASHBOARD_STATBOXES_GET_FAIL';
export const DASHBOARD_STATBOXES_GET_REQUEST = 'DASHBOARD_STATBOXES_GET_REQUEST';
export const DASHBOARD_STATBOXES_GET_SUCCESS ='DASHBOARD_STATBOXES_GET_SUCCESS';

/* USER */
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";
/* PROGRAM */
export const PROGRAM_GET_SUCCESS = "PROGRAM_GET_SUCCESS";
export const PROGRAM_GET_FAIL = "PROGRAM_GET_FAIL";