let initialState = {

    auth: {
        user: null,
    },
    programs: [],
    catalogs: [],
    educators: [],
    privileges: [
      {
        id: 1,
        name: 'Not Available',
        pstudentInscription: true,
        pstudentApproval: true,
        pnotesEntry: true,
        pnotesVisualization: true,
        passitanceEntry: true,
        passitanceVisualization: true,
        pevaluationEntry: true,
        pevaluationVisualization: true,
        pmonitoringEntry: true,
        pmonitoringVisualization: true,
        pindicatorsVisualization: true,
        pindicatorsPVisualization: true,
        pinformationVisualization: true,
        pinformationEntry: true,
        pprogramsVisualization: true,
        pindicatrosRVisualization: true,
        pindicatrosDVisualization: true,
        pindicatrosGVisualization: true,
        pstructureEntry: true,
        pcatalogsEntry: true,
        ppersonalEntry: true,
        ppersonalEvaluationEntry: true,
        ppersonalPassEntry: true,
        ppersonalDataEntry: true,
        pprogramActivation: true,
        pstudentsEntry: true
      },{
        id: 2,
        name: 'Not Available',
        pstudentInscription: true,
        pstudentApproval: true,
        pnotesEntry: true,
        pnotesVisualization: true,
        passitanceEntry: true,
        passitanceVisualization: true,
        pevaluationEntry: true,
        pevaluationVisualization: true,
        pmonitoringEntry: true,
        pmonitoringVisualization: true,
        pindicatorsVisualization: true,
        pindicatorsPVisualization: true,
        pinformationVisualization: true,
        pinformationEntry: true,
        pprogramsVisualization: true,
        pindicatrosRVisualization: true,
        pindicatrosDVisualization: true,
        pindicatrosGVisualization: true,
        pstructureEntry: true,
        pcatalogsEntry: true,
        ppersonalEntry: true,
        ppersonalEvaluationEntry: true,
        ppersonalPassEntry: true,
        ppersonalDataEntry: true,
        pprogramActivation: true,
        pstudentsEntry: true
      },
    ],
    sedes: [],
    users: [],

};

export default initialState;
