INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('municipalidad', 'Municipalidades para usar en las sedes', 0);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('departamento', 'Departamentos de Guatemala donde la fundación trabaja', 0);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('comunidad', 'Comunidades pertencientes al programa', 0);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Fisico', 'Para programas que requieran información fisica', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Colonia', 'Colonia de ubicación', 0);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('nivel', 'Niveles asignados a los grados', 0);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('asistencia', 'Lleva el control de las asistencias posibles', 0);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Mental', 'Lleva el control de las habilidades de la cabeza', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Comprensión lectora', 'Verifica su capacidad para leer', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Educacion', 'Educacion', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Condicion Física', 'Condición física', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.category (name, description, aditional_field) VALUES ('Cocina', 'Cocina', 1);