INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (50, 'Habilidad culinaria', 'df');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (50, 'Experiencia', 'sdf');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (50, 'Altura', '534');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (51, 'Habilidad culinaria', 'dS');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (51, 'Experiencia', 'd');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (51, 'Altura', '24');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (52, 'Habilidad culinaria', 'gk');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (52, 'Experiencia', 'hg');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (52, 'Altura', '445');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (53, 'Habilidad culinaria', 'demo 2');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (53, 'Experiencia', 'demo 2 ');
INSERT INTO cementos_dbprogramasfcfn.dbo.participant_aditional_fields_values (aditional_field_id, intial_value, final_value) VALUES (53, 'Altura', '123');