INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Guateamala', 'text', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Mixco', 'text', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Guatemala', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('El Progreso', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Zacapa', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('El Pajon', 'text', 3);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('La Naranaja', 'text', 3);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Altura', 'number', 7);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Primaria', 'text', 9);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('secundaria', 'text', 9);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('asistio', '1', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('no asistio', '2', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('No asistio. Por enfermedad o lesión', '3', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('No asistio. Por problemas familiares', '4', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('No asistio. Por amenaza o violencia', '5', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Peso', 'number', 7);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Masa corporal', 'number', 7);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Coeficiente intelectual', 'number', 11);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Palabras por minuto', 'number', 13);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Libros leidos', 'number', 13);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('diversificado', 'text', 9);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('IQ', 'number', 14);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Pre-Primaria', 'text', 9);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Chinautla', 'text', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Peten', 'text', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Peten', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Altura', 'number', 15);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Habilidad culinaria', 'text', 16);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Experiencia', 'text', 16);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Chinautla', 'text', 1);