INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Cementos', '4ta calle 5 ave', 'CEM');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Naranja', '17av 18-26', 'NARA');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Calaps', '1A calle 19-25 Zona 15', 'CLPS');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Los Proceres', 'Zona 10', 'LPS');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Oakland', 'zona 10', 'OAK');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Pradera Concepción', 'km 3 carretera a El Salvador', 'PRAC');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Landivar', 'zona 15, km 2 3-a', 'LV');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Marroquin', 'zona 10, 1a -10', 'MARR');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('San Carlos', 'zona 12, 1a - 28', 'SANC');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Liceo Javier', 'zona 12 13-15', 'LJ');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Americano', 'zona 15 99-23', 'AMER');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Valle Verde', 'zona 15 1a-17', 'VALL');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Sede Antigua', 'Antigua 66a-11av', 'ANT');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Sede Mixco', 'mixco 14-28', 'MIX');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Sede Xela', 'xela 1A-14', 'XEL');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Colonia Piña', 'piña, zona 6 14-22', 'PIN');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Colonia Pera', 'Pera, zona 7 18-90', 'PER');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Colonia Naranaja', 'zona 11 colonia naranja 22-33', 'NARA');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Intecap zona 9', 'zona 9, 11-48', 'INT9');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Intecap zona 7', 'zona 7, 22-16', 'INT7');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Intecap zona 10', 'zona 10, 11-44av', 'INT10');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Futeca zona 1', 'zona 1, 13av 18 calle', 'FUT1');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Futeca zona 14', 'zona 14, 15-26', 'FUT14');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Futeca zona 9', 'zona 9, 13calle 15av', 'FUT9');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Holel Barcelo', 'zona 9, 11-22', 'HBAR');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Hotel Intercontinental', 'zona 10, 44-90', 'HINTE');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Hotel Camino Real', 'zona 10, 12-50', 'HCAM');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Hospital el Pilar', 'zona 15, 11-44', 'HPIL');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Hospital general', 'zona 10, 22-10', 'HGEN');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Hospital Herrera G.', 'zona 8, 1-2', 'HHER');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Lago de Atitlan', 'km 15 de la ciuidad', 'LAT');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Lago de Amatitaln', 'Solola, km 190', 'LAM');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Lago de Izabal', 'Izabala km 300', 'LAIZ');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Metropolis', 'Avenida S 10-48', 'METR');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Gotham', 'Avenida 88 ciuidad Gotica', 'GOTH');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('Springfield', 'Avenida Siempreviva 742', 'SPRIN');
INSERT INTO cementos_dbprogramasfcfn.dbo.location (name, address, alias) VALUES ('123', '123', '123');