INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Guateamala', 'text', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Mixco', 'text', 1);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Guatemala', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('El Progreso', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Zacapa', 'text', 2);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('El Pajon', 'text', 3);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('La Naranaja', 'text', 3);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Primaria', 'text', 9);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('secundaria', 'text', 9);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('asistio', '1', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('no asistio', '2', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('No asistio. Por enfermedad o lesión', '3', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('No asistio. Por problemas familiares', '4', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('No asistio. Por amenaza o violencia', '5', 10);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Adicional 1', 'text', 22);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Adicional 2', 'text', 22);
INSERT INTO cementos_dbprogramasfcfn.dbo.catalog (name, type, category) VALUES ('Adicional 1', 'text', 23);